export type InterviewUiLanguage = "hy" | "en" | "ru";

export function interviewUiLanguage(code?: string | null): InterviewUiLanguage {
  const value = (code || "hy").toLowerCase();
  if (value.startsWith("en")) return "en";
  if (value.startsWith("ru")) return "ru";
  return "hy";
}

const COPY = {
  hy: {
    languageName: "հայերեն",
    consentEyebrowFallback: "Հարցազրույց",
    consentTitle: (firstName: string) => `Բարև, ${firstName}`,
    consentIntro: (companyName: string) =>
      `Սա արհեստական բանականությամբ աշխատող հարցազրույց է՝ հասկանալու կրկնվող գործընթացները, որոնք ժամանակ են խլում ${companyName}-ում։`,
    consentDuration: (role: string) => `Սովորաբար տևում է 15–20 րոպե։ Դուք նշված եք որպես ${role}։`,
    consentStore: "Պահվում է խոսակցության տեքստը և կառուցվածքային եզրակացությունները։",
    consentNoAudio: "Հում աուդիո չի պահվում։",
    consentSecrets: "Խնդրում ենք չկիսվել բիզնեսի գաղտնիքներով կամ հաճախորդների անձնական տվյալներով։",
    consentButton: "Համաձայն եմ և սկսել",
    thanksTitle: (firstName: string) => `Շնորհակալություն, ${firstName}`,
    thanksBody: "Հարցազրույցն ավարտված է։ Կարող եք փակել այս էջը։",
    live: "Կապը հաստատված է",
    connecting: "Միանում է…",
    text: "Տեքստային ռեժիմ",
    error: "Ձայնը չհաջողվեց",
    ready: "Պատրաստ է",
    end: "Ավարտել",
    send: "Ուղարկել",
    placeholder: "Գրեք այստեղ, եթե ձայնը հասանելի չէ",
    interviewer: "Հարցազրուցավար",
    speaking: "խոսում է",
    reconnectText: "Ձայնային կապը ընդհատվեց։ Կարող եք շարունակել տեքստով։",
    connectFailed: "Կապը չհաջողվեց",
    tokenFailed: "Չհաջողվեց սկսել ձայնային կապը",
    orbConnecting: "Թույլատրեք խոսափողը զննարկչում",
    orbIdle: "Սեղմեք՝ խոսափողը միացնելու համար",
    orbAiSpeaking: "Հարցազրուցավարը խոսում է",
    orbEnableMic: "Սեղմեք՝ խոսափողը միացնելու համար",
    orbYouSpeaking: "Դուք եք խոսում",
    orbListening: "Լսում է Ձեզ",
    micConnectingTitle: "Թույլատրեք խոսափողը",
    micConnectingBody: "Սեղմեք Allow զննարկչի հարցման վրա։ Մինչև խոսափողը միացված չէ, հարցազրույցը չի սկսվի։",
    micConnectingAction: "Սպասում է թույլտվության…",
    micConnectingHint: "Զննարկիչը հարցնում է վերևում։ Սեղմեք Allow, որպեսզի շարունակեք։",
    micHint: "Խոսափողը միայն հարցազրույցի ընթացքում է օգտագործվում։ Հում ձայն չի պահվում։",
    micDeniedTitle: "Խոսափողը արգելափակված է",
    micDeniedBody:
      "Զննարկիչը արգելել է խոսափողը այս կայքի համար։ Թույլատրեք այն կայքի կարգավորումներում, ապա սեղմեք կրկին փորձել։",
    micUnavailableTitle: "Խոսափող չի գտնվել",
    micUnavailableBody:
      "Միացրեք խոսափողը սարքին կամ ստուգեք, որ այն չի օգտագործվում այլ հավելվածում, ապա կրկին փորձեք։",
    micSessionErrorTitle: "Ձայնային կապը չհաջողվեց",
    micRetry: "Կրկին փորձել",
    micEnableTitle: (name: string) => `Միացրեք խոսափողը, ${name}`,
    micEnableBody: "Հարցազրույցը ձայնային է։ Սեղմեք կոճակը և թույլատրեք խոսափողը, որպեսզի կարողանանք սկսել։",
    micEnableAction: "Միացնել խոսափողը",
    micStep1: "1. Սեղմեք կողպեքի կամ խոսափողի նշանը հասցեի տողում։",
    micStep2: "2. Բացեք կայքի կարգավորումները և գտեք Microphone։",
    micStep3: "3. Ընտրեք Allow, ապա վերադարձեք այստեղ և սեղմեք կրկին փորձել։",
    micStep4: "4. iPhone-ում՝ Settings → Safari → Microphone, ապա թարմացրեք էջը։",
  },
  en: {
    languageName: "English",
    consentEyebrowFallback: "Interview",
    consentTitle: (firstName: string) => `Hello, ${firstName}`,
    consentIntro: (companyName: string) =>
      `This is an AI interview to understand recurring processes that take time at ${companyName}.`,
    consentDuration: (role: string) => `It usually takes 15–20 minutes. You are listed as ${role}.`,
    consentStore: "We store the conversation transcript and structured findings.",
    consentNoAudio: "Raw audio is not stored.",
    consentSecrets: "Please do not share business secrets or personal customer data.",
    consentButton: "I agree and start",
    thanksTitle: (firstName: string) => `Thank you, ${firstName}`,
    thanksBody: "The interview is complete. You can close this page.",
    live: "Connected",
    connecting: "Connecting…",
    text: "Text mode",
    error: "Voice failed",
    ready: "Ready",
    end: "End",
    send: "Send",
    placeholder: "Type here if voice is not available",
    interviewer: "Interviewer",
    speaking: "speaking",
    reconnectText: "The voice connection dropped. You can continue in text.",
    connectFailed: "Connection failed",
    tokenFailed: "Could not start the voice session",
    orbConnecting: "Allow the microphone in the browser",
    orbIdle: "Tap to enable the microphone",
    orbAiSpeaking: "The interviewer is speaking",
    orbEnableMic: "Tap to enable the microphone",
    orbYouSpeaking: "You are speaking",
    orbListening: "Listening to you",
    micConnectingTitle: "Allow the microphone",
    micConnectingBody: "Click Allow on the browser prompt. The interview cannot start until the microphone is on.",
    micConnectingAction: "Waiting for permission…",
    micConnectingHint: "The browser is asking above. Click Allow to continue.",
    micHint: "The microphone is used only during the interview. Raw audio is not stored.",
    micDeniedTitle: "Microphone is blocked",
    micDeniedBody: "The browser blocked the microphone for this site. Allow it in site settings, then try again.",
    micUnavailableTitle: "No microphone found",
    micUnavailableBody: "Connect a microphone or close other apps using it, then try again.",
    micSessionErrorTitle: "Voice connection failed",
    micRetry: "Try again",
    micEnableTitle: (name: string) => `Enable the microphone, ${name}`,
    micEnableBody: "This interview is voice-based. Tap the button and allow the microphone to begin.",
    micEnableAction: "Enable microphone",
    micStep1: "1. Click the lock or microphone icon in the address bar.",
    micStep2: "2. Open site settings and find Microphone.",
    micStep3: "3. Choose Allow, then come back here and try again.",
    micStep4: "4. On iPhone: Settings → Safari → Microphone, then refresh the page.",
  },
  ru: {
    languageName: "Русский",
    consentEyebrowFallback: "Интервью",
    consentTitle: (firstName: string) => `Здравствуйте, ${firstName}`,
    consentIntro: (companyName: string) =>
      `Это интервью с ИИ, чтобы понять повторяющиеся процессы, которые отнимают время в ${companyName}.`,
    consentDuration: (role: string) => `Обычно занимает 15–20 минут. Вы указаны как ${role}.`,
    consentStore: "Сохраняется текст разговора и структурированные выводы.",
    consentNoAudio: "Сырое аудио не сохраняется.",
    consentSecrets: "Пожалуйста, не делитесь бизнес-секретами или персональными данными клиентов.",
    consentButton: "Согласен и начать",
    thanksTitle: (firstName: string) => `Спасибо, ${firstName}`,
    thanksBody: "Интервью завершено. Можно закрыть эту страницу.",
    live: "Связь установлена",
    connecting: "Подключение…",
    text: "Текстовый режим",
    error: "Голос не удался",
    ready: "Готово",
    end: "Завершить",
    send: "Отправить",
    placeholder: "Напишите здесь, если голос недоступен",
    interviewer: "Интервьюер",
    speaking: "говорит",
    reconnectText: "Голосовая связь прервалась. Можно продолжить текстом.",
    connectFailed: "Не удалось подключиться",
    tokenFailed: "Не удалось начать голосовую сессию",
    orbConnecting: "Разрешите микрофон в браузере",
    orbIdle: "Нажмите, чтобы включить микрофон",
    orbAiSpeaking: "Интервьюер говорит",
    orbEnableMic: "Нажмите, чтобы включить микрофон",
    orbYouSpeaking: "Вы говорите",
    orbListening: "Слушает вас",
    micConnectingTitle: "Разрешите микрофон",
    micConnectingBody: "Нажмите Allow в запросе браузера. Пока микрофон выключен, интервью не начнётся.",
    micConnectingAction: "Ожидание разрешения…",
    micConnectingHint: "Браузер спрашивает сверху. Нажмите Allow, чтобы продолжить.",
    micHint: "Микрофон используется только во время интервью. Сырое аудио не сохраняется.",
    micDeniedTitle: "Микрофон заблокирован",
    micDeniedBody: "Браузер заблокировал микрофон для этого сайта. Разрешите его в настройках сайта и попробуйте снова.",
    micUnavailableTitle: "Микрофон не найден",
    micUnavailableBody: "Подключите микрофон или закройте другие приложения, которые его используют, затем попробуйте снова.",
    micSessionErrorTitle: "Голосовая связь не удалась",
    micRetry: "Попробовать снова",
    micEnableTitle: (name: string) => `Включите микрофон, ${name}`,
    micEnableBody: "Интервью голосовое. Нажмите кнопку и разрешите микрофон, чтобы начать.",
    micEnableAction: "Включить микрофон",
    micStep1: "1. Нажмите значок замка или микрофона в адресной строке.",
    micStep2: "2. Откройте настройки сайта и найдите Microphone.",
    micStep3: "3. Выберите Allow, затем вернитесь сюда и попробуйте снова.",
    micStep4: "4. На iPhone: Settings → Safari → Microphone, затем обновите страницу.",
  },
} as const;

export function interviewCopy(language?: string | null) {
  return COPY[interviewUiLanguage(language)];
}
